export default function DisclaimerPage() {
    return (
        <div className="section-padding">
            <div className="container-custom max-w-4xl">
                <h1 className="text-3xl md:text-4xl font-bold mb-8">Disclaimer</h1>

                <div className="prose prose-invert max-w-none space-y-6 text-slate-300">
                    <div className="card p-6 border-amber-500/30 bg-amber-500/5">
                        <h2 className="text-xl font-semibold text-amber-300 mb-4">⚠️ Important Notice</h2>
                        <p className="text-amber-100">
                            The CBAM Calculator tool and all content on this website are provided for
                            <strong> informational and educational purposes only</strong>. Nothing on this
                            website constitutes legal, tax, customs, or professional advice.
                        </p>
                    </div>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">Calculation Estimates</h2>
                        <p>
                            The CBAM cost estimates generated by our calculator are approximations based on:
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>EU default emission values (which include a 10% markup in 2026)</li>
                            <li>Representative EU ETS prices (subject to daily fluctuations)</li>
                            <li>Simplified assumptions about product categories</li>
                            <li>General country-level carbon pricing data</li>
                        </ul>
                        <p className="mt-4">
                            <strong>Actual CBAM costs will differ</strong> based on your specific products,
                            verified supplier emission data, exact EU ETS prices at time of declaration,
                            and other factors we cannot account for.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">Not Professional Advice</h2>
                        <p>
                            This website does not provide and is not a substitute for:
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Legal advice from qualified attorneys</li>
                            <li>Tax advice from certified tax professionals</li>
                            <li>Customs advice from licensed customs brokers</li>
                            <li>Official guidance from EU or member state authorities</li>
                        </ul>
                        <p className="mt-4">
                            For all CBAM compliance decisions, you should consult with qualified professionals
                            who can review your specific circumstances.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">No Liability</h2>
                        <p>
                            We expressly disclaim all liability for any losses, damages, or penalties that may
                            arise from:
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Reliance on our calculator estimates for business decisions</li>
                            <li>Incorrect or outdated information on this website</li>
                            <li>Misinterpretation of CBAM regulations</li>
                            <li>Technical errors or service unavailability</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">Regulatory Changes</h2>
                        <p>
                            EU CBAM regulations are subject to ongoing implementation and potential amendments.
                            We make reasonable efforts to keep our information current, but cannot guarantee
                            that all content reflects the latest regulatory developments. Always verify
                            information with official EU sources.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">External Links</h2>
                        <p>
                            This website may contain links to external resources, including official EU
                            documents. We are not responsible for the content, accuracy, or availability
                            of external websites.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">No Endorsement</h2>
                        <p>
                            Reference to any specific products, services, or organizations does not constitute
                            or imply endorsement by CBAM Calculator.
                        </p>
                    </section>

                    <div className="card p-6 mt-8">
                        <p className="text-center text-slate-400">
                            By using this website, you acknowledge that you have read and understood this
                            disclaimer and agree to its terms.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
